####################################
makeup:
  dataset:
    dataset_dir: "dataset/data/instagram"

  model:
    num_features: 7
    image_channels: 3
    image_size: 128
    gan_type: gan

  trainer:
    num_gpu: 1
    num_workers: 32
    results_dir: "results/"

    batch_size: 128

    D_optim_config:
      optim_choice: adam
      lr: 2.0e-4
      momentum: 0.9
      betas: [0.5, 0.9]

    G_optim_config:
      optim_choice: adam
      lr: 1.0e-4
      momentum: 0.9
      betas: [0.5, 0.9]

    constants:
      applier_adversarial: 2.
      remover_adversarial: 2.
      style_adversarial: 1.
      before_identity_robustness: 2.
      after_identity_robustness: 0.
      style_identity_robustness: 0.
      applier_mask_sparsity: 2.
      remover_mask_sparsity: 0.
      applier_D_grad_penalty: 10.
      remover_D_grad_penalty: 10.
      style_D_grad_penalty: 10.

    D_iters: 3

    report_interval: 10
    generate_grid_interval: 6

####################################
makeup-test:
  dataset:
    dataset_dir: "dataset/data/instagram"

  model:
    num_features: 5
    image_channels: 3
    image_size: 32
    gan_type: wgan-gp

  trainer:
    num_gpu: 0
    num_workers: 4
    results_dir: "results/"
    batch_size: 4
    D_iters: 1
    report_interval: 10
    generate_grid_interval: 10

    constants:
      applier_adversarial: 1
      remover_adversarial: 1
      style_adversarial: 1
      before_identity_robustness: 1
      after_identity_robustness: 1
      style_identity_robustness: 1
      applier_mask_sparsity: 1
      remover_mask_sparsity: 1
      applier_D_grad_penalty: 1
      remover_D_grad_penalty: 1
      style_D_grad_penalty: 1

####################################
dcgan:
  dataset:
    dataset_dir: "dataset/data/processing/faces"

  model:
    num_latents: 128
    num_features: 64
    image_channels: 3
    image_size: 64
    gan_type: gan

  trainer:
    name: "trainer"
    results_dir: "results/"
    load_model_path:

    num_gpu: 1
    num_workers: 2
    batch_size: 4

    D_optim_config:
      optim_choice: sgd
      lr: 1.0e-4
      momentum: 0.
      betas: [0.9, 0.999]

    G_optim_config:
      optim_choice: sgd
      lr: 1.0e-4
      momentum: 0.
      betas: [0.9, 0.999]

    D_iters: 5
    clamp: [-0.01, 0.01]
    gp_coeff: 10.

    report_interval: 50
    generate_grid_interval: 200

####################################
wgan:
  dataset:
    dataset_dir: "dataset/data/processing/faces"

  model:
    num_latents: 128
    num_features: 64
    image_channels: 3
    image_size: 64
    gan_type: wgan

  trainer:
    name: "trainer"
    results_dir: "results/"
    load_model_path:

    num_gpu: 1
    num_workers: 2
    batch_size: 4

    D_optim_config:
      optim_choice: rmsprop
      lr: 5.0e-5
      momentum: 0.
      betas: [0.5, 0.9]

    G_optim_config:
      optim_choice: rmsprop
      lr: 5.0e-5
      momentum: 0.
      betas: [0.5, 0.9]

    D_iters: 5
    clamp: [-0.01, 0.01]
    gp_coeff: 10.

    report_interval: 50
    generate_grid_interval: 200

####################################
wgan-gp:
  dataset:
    dataset_dir: "dataset/data/processing/faces"

  model:
    num_latents: 128
    num_features: 64
    image_channels: 3
    image_size: 64
    gan_type: wgan-gp

  trainer:
    name: "trainer"
    results_dir: "results/"
    load_model_path:

    num_gpu: 1
    num_workers: 2
    batch_size: 4

    D_optim_config:
      optim_choice: adam
      lr: 1.0e-4
      momentum: 0.
      betas: [0.0, 0.9]

    G_optim_config:
      optim_choice: adam
      lr: 1.0e-4
      momentum: 0.
      betas: [0.0, 0.9]

    D_iters: 5
    clamp: [-0.01, 0.01]
    gp_coeff: 10.

    report_interval: 50
    generate_grid_interval: 200

